// Code generated by tools/gen/ast. DO NOT EDIT.

package parser

import "github.com/leonardinius/golox/internal/token"

// ExprVisitor is the interface that wraps the Visit method.
type ExprVisitor interface {
	VisitBinary(v *Binary) any
	VisitGrouping(v *Grouping) any
	VisitLiteral(v *Literal) any
	VisitUnary(v *Unary) any
}

type Expr interface {
	Accept(v ExprVisitor) any
}

type Binary struct {
	Left     Expr
	Operator *token.Token
	Right    Expr
}

var _ Expr = (*Binary)(nil)

func (e *Binary) Accept(v ExprVisitor) any {
	return v.VisitBinary(e)
}

type Grouping struct {
	Expression Expr
}

var _ Expr = (*Grouping)(nil)

func (e *Grouping) Accept(v ExprVisitor) any {
	return v.VisitGrouping(e)
}

type Literal struct {
	Value any
}

var _ Expr = (*Literal)(nil)

func (e *Literal) Accept(v ExprVisitor) any {
	return v.VisitLiteral(e)
}

type Unary struct {
	Operator *token.Token
	Right    Expr
}

var _ Expr = (*Unary)(nil)

func (e *Unary) Accept(v ExprVisitor) any {
	return v.VisitUnary(e)
}
