// Code generated by tools/gen/ast. DO NOT EDIT.

package parser

import "github.com/leonardinius/golox/internal/token"

// StmtVisitor is the interface that wraps the Visit method.
type StmtVisitor interface {
	VisitStmtExpression(expression *StmtExpression) (any, error)
	VisitStmtPrint(print *StmtPrint) (any, error)
	VisitStmtVar(v *StmtVar) (any, error)
}

type Stmt interface {
	Accept(v StmtVisitor) (any, error)
}

type StmtExpression struct {
	Expression Expr
}

var _ Stmt = (*StmtExpression)(nil)

func (e *StmtExpression) Accept(v StmtVisitor) (any, error) {
	return v.VisitStmtExpression(e)
}

type StmtPrint struct {
	Expression Expr
}

var _ Stmt = (*StmtPrint)(nil)

func (e *StmtPrint) Accept(v StmtVisitor) (any, error) {
	return v.VisitStmtPrint(e)
}

type StmtVar struct {
	Name        *token.Token
	Initializer Expr
}

var _ Stmt = (*StmtVar)(nil)

func (e *StmtVar) Accept(v StmtVisitor) (any, error) {
	return v.VisitStmtVar(e)
}
